on:
  push:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    name: windows-latest
    steps:
      - run: |
          g++ main.cpp -o a.exe
          Measure-Command ./a.exe C
          Measure-Command ./a.exe Japanese
