on:
  push:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    name: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
      
      - run: |
          install.packages("cpp11")
          cpp11::cpp_source(
            code = 
              '#include <regex>
          [[cpp11::register]]
          void foo() {
            std::regex reg("[0-9]");
          }
          ')
          # works
          Sys.setlocale("LC_COLLATE", 'English')
          system.time(foo())
          # freezes
          Sys.setlocale("LC_COLLATE", 'Japanese')
          system.time(foo())
        shell: Rscript {0}
