on:
  push:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    name: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
      
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_cran("cpp11")
        shell: Rscript {0}

      - name: Test
        run: |
          cpp11::cpp_source(
            code = 
              '#include <regex>
          [[cpp11::register]]
          void foo() {
            std::regex reg("[0-9]");
          }
          ')
          cat("system.time() w/ LC_COLLATE=English \n")
          Sys.setlocale("LC_COLLATE", 'English')
          system.time(foo())
          cat("system.time() w/ LC_COLLATE=Japanese \n")
          Sys.setlocale("LC_COLLATE", 'Japanese')
          system.time(foo())
        shell: Rscript {0}
